### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zhoupengfei001** [chimmhuang/chimm.excel#5]
数据列在A~Z之间是正常的，但是在列数超过Z列之后会出现一点问题，比如第三列数据很乱，第AA列数据丢失等问题

**Comment by chimmhuang** [comment]
以下是聊天记录，详细描述了该bug（我怕我自己忘了，贴上来以后好改）
--------------
您好  我在做那个导出的时候  我需要导出86列数据  然后做的时候导出来有问题 在第AB列的时候报错，AA列没有数据  C列数据又丢失了   不知道这是不是一个bug  麻烦您看到了回复一下哈
